### ISSUE TITLE
Noms latins

### ISSUE THREAD

**Issue by Florulenta** [Instelce/Plantaludum#1]
Bonjour,

Merci pour ce jeu très sympa !
Une remarque (ce n'est pas un bug fonctionnel) l'application semble afficher le premier nom latin qu'elle trouve pour une espèce. Ce n'est que rarement le nom valide, connu des botanistes, c'est le plus souvent une appelation oubliée de tous :-)
Le problème doit se situer dans votre API qui interroge Tela, il faudrait qu'elle vérifie que le "Numéro nomenclatural"  soit identique au "Numéro nomenclatural du nom retenu" pour récupérer le bon nom latin.

Cordialement

**Comment by Instelce** [comment]
Bonjour, merci du retour !

Je viens de changer les valeurs par défaut pour les boutons du quiz.
Est-ce que vous pouvez me dire si les infos sont maintenant correctes ?

D'ailleurs, dans les paramètres vous pouvez changer ces valeurs : 
![Capture d’écran du 2024-03-07 15-49-54 1(1)](https://github.com/Instelce/Plantaludum/assets/65083350/9358b693-d827-414b-9b09-754a46f95455)

**Comment by Florulenta** [comment]
> Le 7 mars 2024 à 16:14, Célestin ***@***.***> a écrit :
> 
> 
> Bonjour, merci du retour !
> 
> Je viens de changer les valeurs par défaut pour les boutons du quiz.
> Est-ce que vous pouvez me dire si les infos sont maintenant correctes ?
> 
> D'ailleurs, dans les paramètres vous pouvez changer ces valeurs :
> Capture.d.ecran.du.2024-03-07.15-49-54.1.1.png (view on web) <https://github.com/Instelce/Plantaludum/assets/65083350/9358b693-d827-414b-9b09-754a46f95455>
C’est du rapide ;-)

C’est parfait comme ça !

Merci


Ludovic

**Comment by Instelce** [comment]
Trop bien, merci à vous !
